In [1]:
import numpy as np

### Task 1
#### Complete tasks, using
* NumPy functions
* iterative constructions (cycles, lists inclusions etc.)

* 1:
    ##### Enter number n, generate n x n array of structure  
    5  
    [[1 0 0 0 0]  
     [0 2 0 0 0]  
     [0 0 3 0 0]  
     [0 0 0 4 0]  
     [0 0 0 0 5]]  
     with numbers from 1 to n on main diagonal.

In [2]:
%%timeit -n 100 -r 10
# NumPy
def task_1(n):
    matrix = np.zeros((n, n))
    np.fill_diagonal(matrix, np.arange(1, n+1))
    return matrix
    
    
task_1(100)

8.01 µs ± 1.21 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [3]:
%%timeit -n 100 -r 10
# Iterative
def task_1(n):
    return [[i if i == j else 0 for j in range(1, n+1)] for i in range(1, n+1)]
    
    
task_1(100)

590 µs ± 55.4 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


* 6:
    ##### Enter array, change all non-zero elements to -1  
    3 4 0 9 7 0 6 0 4 0 3  
    [-1 -1 0 -1 -1 0 -1 0 -1 0 -1]

In [4]:
%%timeit -n 100 -r 10
# NumPy
def task_6(array):
    arr = np.array(array)
    arr[arr != 0] = -1
    return arr
    
task_6([-49, -48, -45, -43, -41, -40, -39, -38, -37, -35, -32, -31, -29, -28, -23, -22, -21, -20, -19, -17, -16, -14, -13, -12, -10, -9, -8, -6, -5, -3, -2, -1, 2, 6, 8, 11, 16, 20, 21, 22, 25, 26, 27, 31, 37, 39, 42, 44, 48, 50])

5.71 µs ± 553 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [5]:
%%timeit -n 100 -r 10
# Iterative
def task_6(array):
    for i in range(len(array)):
        if array[i] != 0:
            array[i] = -1
    return array
    
task_6([-49, -48, -45, -43, -41, -40, -39, -38, -37, -35, -32, -31, -29, -28, -23, -22, -21, -20, -19, -17, -16, -14, -13, -12, -10, -9, -8, -6, -5, -3, -2, -1, 2, 6, 8, 11, 16, 20, 21, 22, 25, 26, 27, 31, 37, 39, 42, 44, 48, 50])

4.05 µs ± 169 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


* 7:
    ##### Enter array, change all zero elements to -1  
    3 4 0 6 5 0 3 0 4  
    [ 3 4 -1 6 5 -1 3 -1 4]

In [6]:
%%timeit -n 100 -r 10
# NumPy
def task_7(array):
    arr = np.array(array)
    arr[arr == 0] = -1
    return arr
    
task_7([-49, -48, -45, -43, -41, -40, -39, -38, -37, -35, -32, -31, -29, -28, -23, -22, -21, -20, -19, -17, -16, -14, -13, -12, -10, -9, -8, -6, -5, -3, -2, -1, 2, 6, 8, 11, 16, 20, 21, 22, 25, 26, 27, 31, 37, 39, 42, 44, 48, 50])

4.96 µs ± 287 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [7]:
%%timeit -n 100 -r 10
# Iterative
def task_7(array):
    for i in range(len(array)):
        if array[i] == 0:
            array[i] = -1
    return array
    
task_7([-49, -48, -45, -43, -41, -40, -39, -38, -37, -35, -32, -31, -29, -28, -23, -22, -21, -20, -19, -17, -16, -14, -13, -12, -10, -9, -8, -6, -5, -3, -2, -1, 2, 6, 8, 11, 16, 20, 21, 22, 25, 26, 27, 31, 37, 39, 42, 44, 48, 50])

2.57 µs ± 83.3 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


* 9:
    ##### Enter number n, create array of values from n to 0  
    10  
    [10 9 8 7 6 5 4 3 2 1 0]

In [8]:
%%timeit -n 100 -r 10
# NumPy
def task_9(n):
    return np.arange(n, -1, -1)

task_9(100)

The slowest run took 8.59 times longer than the fastest. This could mean that an intermediate result is being cached.
1.51 µs ± 1.83 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [9]:
%%timeit -n 100 -r 10
# Iterative
def task_9(n):
    return [i for i in range(n, -1, -1)]

task_9(100)

3.43 µs ± 741 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


* 10:
    ##### Enter numbers n and m, create array of random values n x m and calculate min, max, mean and standard deviation, round to 3 decimal digits   
    4 5  
    min: 0.038  
    max: 0.946  
    mean: 0.593  
    standard deviation: 0.302

In [10]:
%%timeit -n 100 -r 10
# NumPy
def task_10(n, m):
    matrix = np.random.random((n, m))
    minimum = np.min(matrix).round(3)
    maximum = np.max(matrix).round(3)
    mean = np.mean(matrix).round(3)
    std_dev = np.std(matrix).round(3)
    return minimum, maximum, mean, std_dev

task_10(10, 20)

80.4 µs ± 3.08 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [11]:
import random
import math

In [12]:
%%timeit -n 100 -r 10
# Iterative  
def task_10(n, m):
    matrix = [[random.uniform(0, 1) for j in range(m)] for i in range(n)]
    
    minimum = 2
    maximum = -1
    mean = 0
    std_dev = 0
    summ = 0
    
    for i in range(n):
        for j in range(m):
            if matrix[i][j] < minimum:
                minimum = matrix[i][j]
            if matrix[i][j] > maximum:
                maximum = matrix[i][j]
            summ += matrix[i][j]
    
    mean = summ / (n * m)
    
    summ = 0
    for i in range(n):
        for j in range(m):
            summ += (matrix[i][j] - mean) ** 2
    std_dev = math.sqrt(summ / (n * m))
            
    return minimum, maximum, mean, std_dev

task_10(10, 20)

170 µs ± 23 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


* 11:
    ##### Create n x n array of ones and add border with zeros  
    4  
    [[0 0 0 0 0 0]  
    [0 1 1 1 1 0]  
    [0 1 1 1 1 0]  
    [0 1 1 1 1 0]  
    [0 1 1 1 1 0]  
    [0 0 0 0 0 0]]

In [13]:
%%timeit -n 100 -r 10
# NumPy
def task_11(n):
    matrix = np.ones((n, n))
    return np.pad(matrix, pad_width=1, mode='constant', constant_values=0)

task_11(100)

46.1 µs ± 2.98 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [14]:
%%timeit -n 100 -r 10
# Iterative
def task_11(n):
    matrix = [[1 for j in range(n)] for i in range(n)]

    matrix.insert(0, [0 for j in range(n)])
    matrix.append([0 for j in range(n)])
    
    for i in range(n + 2):
        matrix[i].insert(0, 0)
        matrix[i].append(0)
        
    return matrix
    
task_11(100)

365 µs ± 41.7 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


* 15:
    ##### Fill even columns of n x n array with with ones and odd columns with zeros  
    5  
    [[0 1 0 1 0]  
    [0 1 0 1 0]  
    [0 1 0 1 0]  
    [0 1 0 1 0]  
    [0 1 0 1 0]]

In [15]:
%%timeit -n 100 -r 10
# NumPy
def task_15(n):
    matrix = np.zeros((n, n))
    matrix[:, 1::2] = 1
    return matrix

task_15(100)

8.12 µs ± 1.56 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [16]:
%%timeit -n 100 -r 10
# Iterative
def task_15(n):
    matrix = [[0 if j % 2 == 0 else 1 for j in range(n)] for i in range(n)]
    return matrix

task_15(100)

718 µs ± 27.7 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


* 17:
    ##### Fill array with values from 0 to n, replace all values < n/2 and > 3n/4 with their opposites  
    10  
    [ 0 -1 -2 -3 -4 5 6 7 -8 -9 -10]

In [17]:
%%timeit -n 100 -r 10
# NumPy
def task_17(n):
    array = np.arange(n+1)
    return np.where(array < n/2, -array, np.where(array > 3 * n/4, -array, array))

task_17(100)

11.9 µs ± 4.2 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [18]:
%%timeit -n 100 -r 10
# Iterative
def task_17(n):
    return [-i if (i < n/2 or i > 3 * n/4) else i for i in range(n + 1)]
    

task_17(100)

18.6 µs ± 1.29 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


* 18:
    ##### Generate array of n random numbers in range [0, 99), calculate number of unique numbers in sequence  
    30  
    In sequence [ 5 77 15 21 8 44 58 77 6 49 35 35 25 3 51 65 73 81 67 78 85 68 40 77 58 1 10 9 59 13] - 26 unique numbers

In [19]:
%%timeit -n 100 -r 10
# NumPy
def task_18(n):
    return len(np.unique(np.random.randint(0, 100, n)))

task_18(100)

27.1 µs ± 4.89 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [20]:
%%timeit -n 100 -r 10
# Iterative
def task_18(n):
    return len(set([random.randrange(0, 100) for i in range(n)]))  

task_18(100)

78.6 µs ± 10.6 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


### Task 2
#### Solving system of linear equations with Cramer's rule
___
**System**:
$$
\begin{cases}
x_1 + x_2 + 2x_3 + 3x_4 = 1 \\
3x_1 - x_2 - x_3 - 2 x_4 = -4 \\
2x_1 - 3x_2 - x_3 - x_4 = -6 \\
x_1 + 2x_2 + 3x_3 - x_4 = -4
\end{cases}
$$

Check afterwards, using:
* matrix multiplication
* inverse matrix
* function ```numpy.linalg.solve()```

In [21]:
matrix = np.array([
    [1, 1, 2, 3],
    [3, -1, -1, -2],
    [2, -3, -1, -1],
    [1, 2, 3, -1]
])

results = np.array([1, -4, -6, -4])


def cramer(matrix, results):
    det = np.linalg.det(matrix)
    size = matrix.shape[0]
    
    if np.allclose(det, 0):
        print("Determinant is zero, aborting.")
        return solution
    
    solution = np.zeros(size)
    
    for i in range(size):
        temp_matrix = np.copy(matrix)
        temp_matrix[:, i] = np.copy(results)
        solution[i] = np.linalg.det(temp_matrix) / det   
    
    return solution

  
    
solution_cramer = cramer(matrix, results)
print(f"Naive result: {solution_cramer}") 

solution_numpy = np.linalg.solve(matrix, results)
print(f"NumPy result: {solution_numpy}\n")
assert np.allclose(solution_numpy, solution_cramer)

check_mult = np.dot(matrix, solution_cramer)
print("Check with matrix multiplication: ")
print(f"Expected value {results}")
print(f"Got value {check_mult}\n")
assert np.allclose(results, check_mult)

check_inv = np.dot(np.linalg.inv(matrix), results)
print("Check with inverse matrix: ")
print(f"Expected value {check_inv}")
print(f"Got value {solution_cramer}\n")
assert np.allclose(check_inv, solution_cramer)

Naive result: [-0.55555556  1.88888889 -2.          1.22222222]
NumPy result: [-0.55555556  1.88888889 -2.          1.22222222]

Check with matrix multiplication: 
Expected value [ 1 -4 -6 -4]
Got value [ 1. -4. -6. -4.]

Check with inverse matrix: 
Expected value [-0.55555556  1.88888889 -2.          1.22222222]
Got value [-0.55555556  1.88888889 -2.          1.22222222]



### Task 3
#### Evaluating matrix expression
___
Expression: $2(A + B)(2B - A)$,

where 
$
A =
\begin{pmatrix}
2 & 3 & -1 \\
4 & 5 & 2 \\
-1 & 0 & 7
\end{pmatrix},
B = 
\begin{pmatrix}
-1 & 0 & 5 \\
0 & 1 & 3 \\
2 & -2 & 4
\end{pmatrix}
$

Evaluate, using:
* NumPy functions
* iterative constructions (cycles, lists inclusions etc.)

For both versions calculate time and draw conclusions.

In [22]:
A = [
    [2, 3, -1],
    [4, 5, 2],
    [-1, 0, 7]
]

A_ = np.array(A)


B = [
    [-1, 0, 5],
    [0, 1, 3],
    [2, -2, 4]
]

B_ = np.array(B)


def mult_matrices(A, B):
    a_rows, a_cols = len(A), len(A[0])
    b_rows, b_cols = len(B), len(B[0])
    if a_cols != b_rows:
        print("Wrong dimensions, multiplication is impossible.")
        return []
    
    return [[sum([x*y for (x, y) in zip(row, col)]) for col in zip(*B)] for row in A]
    
def add_matrices(A, B):
    a_rows, a_cols = len(A), len(A[0])
    b_rows, b_cols = len(B), len(B[0])
    if a_rows != b_rows or a_cols != b_cols:
        print("Wrong dimensions, addition is impossible.")
        return []

    return [[A[i][j] + B[i][j] for j in range(a_cols)] for i in range(a_rows)]

def scalar_mult_matrix(scalar, matrix):
    rows, cols = len(matrix), len(matrix[0])
    return [[matrix[i][j] * scalar for j in range(cols)] for i in range(rows)]

In [23]:
%%timeit -n 100 -r 10
2 * (A_ + B_) @ (2 * B_ - A_)

4.09 µs ± 587 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [24]:
%%timeit -n 100 -r 10
scalar_mult_matrix(
    2, 
    mult_matrices(
        add_matrices(A, B), 
        add_matrices(
            scalar_mult_matrix(2, B),
            scalar_mult_matrix(-1, A)
        )
    )
)


25.6 µs ± 4.47 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [25]:
result_numpy = 2 * (A_ + B_) @ (2 * B_ - A_)
result_iterative = scalar_mult_matrix(
    2, 
    mult_matrices(
        add_matrices(A, B), 
        add_matrices(
            scalar_mult_matrix(2, B),
            scalar_mult_matrix(-1, A)
        )
    )
)

assert np.allclose(result_numpy, result_iterative)